# Generated by Django 3.1.4 on 2020-12-23 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceMeasure',
            fields=[
                ('EntranceID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Data', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
