# Generated by Django 3.0 on 2020-12-31 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('u_login', models.CharField(default='_Login_is_non_provided', max_length=30, unique=True)),
                ('u_password', models.CharField(blank=True, max_length=30, null=True)),
                ('u_role', models.IntegerField(default='2')),
                ('u_name', models.CharField(blank=True, max_length=150, null=True)),
                ('id_device', models.ManyToManyField(null=True, to='app.Devices')),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
        ),
    ]
