# Generated by Django 3.0 on 2020-12-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_device',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_device',
            field=models.ManyToManyField(null=True, to='app.Devices'),
        ),
    ]
