# Generated by Django 3.1.4 on 2021-02-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_login',
            field=models.CharField(default='Login', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.BooleanField()),
                ('id_adapters', models.ForeignKey(limit_choices_to=2, on_delete=django.db.models.deletion.CASCADE, to='app.adapters')),
                ('id_devices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.devices')),
            ],
        ),
    ]
