# Generated by Django 3.1.4 on 2020-12-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201228_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestousers',
            name='id_device',
        ),
        migrations.AddField(
            model_name='devicestousers',
            name='id_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.devices'),
        ),
        migrations.RemoveField(
            model_name='devicestousers',
            name='id_user',
        ),
        migrations.AddField(
            model_name='devicestousers',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
