# Generated by Django 3.1.4 on 2020-12-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201230_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_django',
            new_name='user_auth',
        ),
    ]
